<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGGzp1r4\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGGzp1r4/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGGzp1r4.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGGzp1r4\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGGzp1r4\App_KernelDevDebugContainer([
    'container.build_hash' => 'GGzp1r4',
    'container.build_id' => '1cf9205e',
    'container.build_time' => 1681655137,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGGzp1r4');
