<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHj9ex2C\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHj9ex2C/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHj9ex2C.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHj9ex2C\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHj9ex2C\App_KernelDevDebugContainer([
    'container.build_hash' => 'Hj9ex2C',
    'container.build_id' => 'c3300cd9',
    'container.build_time' => 1681591117,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHj9ex2C');
